### ISSUE TITLE
How to mock child operations in tests

### ISSUE THREAD

**Issue by alexandru-calinoiu** [MortenChristiansen/Overflow.net#6]
I have an Operation that depends on a couple child operations, I would like to mock their output in my tests, what will be the best way to achieve this?

**Comment by MortenChristiansen** [comment]
An approach might be to create a custom `IOperationResolver` rather than using the built in `SimpleOperationResolver`. If you use interfaces for your operations, the new resolver could look for mock implementations to return instead. Just copy the build in implementation and replace the logic that instantiates operations using `Activator.CreateInstance(...)`. Each operation interface would have to implement the `IOperation` interface but would not need to have any members itself, unless needed by the test. I think that should do it. If you try it, let me know how it goes. Otherwise, I might give it a go later this week.

**Comment by MortenChristiansen** [comment]
I added the `FakeOperationResolver` class in the latest version. It allows you to register operation instances as fakes, replacing specific child operations when requested. You need to either use the `Workflow.Configure<T>()` method and supply the resolver or call the `Operation.Initialize()` method with a `WorkflowConfiguration` instance with the resolver.

**Comment by alexandru-calinoiu** [comment]
Thank you, will take a look.
